version: "3.8"

services:
    nginx:
        image: nginx:latest
        container_name: ramarmalia-nginx
        restart: always
        depends_on:
            - ramarmaliafrankenphp
        ports:
            - "80:80"
        volumes:
            - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
            - ./docker/nginx/conf.d:/etc/nginx/conf.d:ro
            - .:/app # Tambahkan bind mount agar nginx bisa membaca file Laravel langsung
        networks:
            - laravel_network

    ramarmaliafrankenphp:
        build:
            context: . # Menentukan direktori build (root proyek)
            dockerfile: Dockerfile # Menentukan Dockerfile yang digunakan
        container_name: ramarmalia-laravel
        restart: always
        depends_on:
            - mysql
            - redis
        ports:
            - "8081:8000"
        networks:
            - laravel_network
        environment:
            DB_HOST: mysql
            DB_DATABASE: sepatu
            DB_USERNAME: root
            DB_PASSWORD: root
            CACHE_DRIVER: redis
            SESSION_DRIVER: redis
            REDIS_HOST: redis
        volumes:
            - .:/app # Tambahkan agar kode Laravel di luar container tetap sinkron
            - ./docker/storage:/app/storage
            - ./docker/php/php.ini:/usr/local/etc/php/php.ini

    mysql:
        image: mariadb:10.6
        container_name: ramarmalia-mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: sepatu
        ports:
            - "3307:3306"
        volumes:
            - ./docker/mysql:/var/lib/mysql # Hanya gunakan named volume, hapus bind mount
        networks:
            - laravel_network

    redis:
        image: redis:alpine
        container_name: ramarmalia-redis
        restart: always
        ports:
            - "6378:6379"
        volumes:
            - ramarmalia-redis:/data
        networks:
            - laravel_network

networks:
    laravel_network:
        driver: bridge

volumes:
    ramarmalia-data:
        driver: local
    ramarmalia-redis:
        driver: local
